In [30]:
import os
import torch

In [31]:
os.chdir("/media/udayanga/data_2/SSD_new_github/SSD-pytorch/")

In [32]:
mmm = torch.load("./weights/SSD.pth")

In [33]:
mmm["model_state_dict"]

OrderedDict([('feature_extractor.feature_extractor.0.weight',
              tensor([[[[-1.0767e-02, -1.1742e-02, -1.8304e-02,  ..., -2.9641e-02,
                         -1.5156e-03,  6.3185e-04],
                        [-1.1411e-02, -1.8297e-02, -2.2065e-02,  ..., -5.0135e-02,
                         -5.2731e-02, -3.9165e-02],
                        [ 3.8820e-02,  2.6826e-02,  3.4030e-02,  ...,  6.0620e-02,
                          2.3257e-02,  2.8051e-02],
                        ...,
                        [-1.5795e-04,  2.6693e-02,  2.7804e-02,  ..., -1.7314e-02,
                          1.4631e-02,  5.3360e-02],
                        [-1.0605e-02,  4.4852e-03,  4.9318e-02,  ...,  2.9766e-02,
                         -3.7117e-03,  1.8340e-02],
                        [-4.6146e-02, -5.7340e-02, -8.0473e-02,  ..., -4.1939e-02,
                         -4.6624e-02, -2.7425e-02]],
              
                       [[ 5.1199e-04,  1.4859e-02,  2.3592e-02,  ...,  5.8536e-03,


In [8]:
from src.model import SSD
from src.utils import generate_dboxes, Encoder, coco_classes
from src.model import ResNet

In [9]:
model = SSD(backbone=ResNet(), num_classes=len(coco_classes))

/media/udayanga/data_2/miniconda3/envs/udaya/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/media/udayanga/data_2/miniconda3/envs/udaya/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [22]:
list(model.feature_extractor.backbone.children())[:7]

[Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False),
 BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True),
 ReLU(inplace=True),
 MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False),
 Sequential(
   (0): Bottleneck(
     (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
     (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
     (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
     (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (relu): ReLU(inplace=True)
     (downsample): Sequential(
       (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
       (1): BatchNorm2d(256, eps=1e-05, momentum

In [23]:
import numpy as np

In [15]:
dd = np.array([2,4,6,8,12])

In [25]:
list(model.feature_extractor.backbone.children())[:7][-1][0]

Bottleneck(
  (conv1): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
  (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
  (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (downsample): Sequential(
    (0): Conv2d(512, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (1): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
)

In [1]:
import numpy as np
 

In [2]:
steps = [8, 16, 32, 64, 100, 300]
fig_size = 300

In [3]:
fk = fig_size / np.array(steps)

In [6]:
fk

array([37.5   , 18.75  ,  9.375 ,  4.6875,  3.    ,  1.    ])

In [9]:
import os
os.path.join("/home/udayanga","train_imgs.txt").dtype

AttributeError: 'str' object has no attribute 'dtype'

In [11]:
import glob

base_path = "/media/udayanga/data_2/latest_dataset"
bbb = glob.glob(base_path + "/*/npz_files_event_based/*/*/*.npz")

In [18]:
cc = []

In [19]:
for ss in bbb:
    cc.append(ss.rsplit("/",1)[1])

In [22]:
len(list(set(cc)))

5995

In [23]:
len(cc)

6034

In [24]:
with open("/media/udayanga/data_2/latest_dataset/test_files_event_based.txt") as f:
    sss = f.readlines()

In [28]:
ddd = []
for file in sss:
    ddd.append(file.rsplit("/",1)[1].rstrip())

In [31]:
len(list(set(ddd)))

1543

In [32]:
org = []

In [33]:
sub1 = [{"a" : 23},{"a" : 43},{"a" : 35}]
sub2 = [{"b" : 23},{"c" : 43},{"b" : 35}]


In [34]:
org.extend(sub1)

In [35]:
org.extend(sub2)

In [36]:
org

[{'a': 23}, {'a': 43}, {'a': 35}, {'b': 23}, {'c': 43}, {'b': 35}]

In [1]:
import numpy as np

In [2]:
A = np.array([[1,0.552,0.678],[2., 0.331, 0.2134],[0.,0.5432, 0.8753]])

In [3]:
A

array([[1.    , 0.552 , 0.678 ],
       [2.    , 0.331 , 0.2134],
       [0.    , 0.5432, 0.8753]])

In [4]:
A.shape

(3, 3)

In [11]:
b = A.astype(np.float32)

In [15]:
b[:,1:] * 3.4

array([[1.8768001 , 2.3051999 ],
       [1.1254001 , 0.72556007],
       [1.8468801 , 2.97602   ]], dtype=float32)

In [16]:
b

array([[1.    , 0.552 , 0.678 ],
       [2.    , 0.331 , 0.2134],
       [0.    , 0.5432, 0.8753]], dtype=float32)

In [17]:
b

array([[1.    , 0.552 , 0.678 ],
       [2.    , 0.331 , 0.2134],
       [0.    , 0.5432, 0.8753]], dtype=float32)

In [1]:
import numpy as np
import os

In [3]:
base_path = "/media/udayanga/data_2/latest_dataset_2/latest_dataset/"
text_file = "/media/udayanga/data_2/latest_dataset_2/latest_dataset/night_outdoor_and_daytime_train_files_event_based.txt"
with_anns_list = []
count = 0
with open(text_file,"r") as f:
    files = f.readlines()
    files = [file.rstrip() for file in files]
    for file in files:
        data = np.load(os.path.join(base_path,file))
        anns = data["ann_array"]
        if anns.any():
            with_anns_list.append(file)
        else:
            print("no anns for ",file)
        count += 1
print("There are {} anns originally ".format(count))

There are 4700 anns originally 


In [12]:
len(with_anns_list)

4668

In [13]:
with_anns_list

['at_DTU/npz_files_image_based/spalling/synth_dtu_spall_10/synth_dtu_spall_10_157782.npz',
 'at_DTU/npz_files_image_based/spalling/synth_dtu_spall_10/synth_dtu_spall_10_2860108.npz',
 'at_DTU/npz_files_image_based/spalling/synth_dtu_spall_10/synth_dtu_spall_10_5134720.npz',
 'at_DTU/npz_files_image_based/spalling/synth_dtu_spall_10/synth_dtu_spall_10_7120126.npz',
 'at_DTU/npz_files_image_based/spalling/synth_dtu_spall_10/synth_dtu_spall_10_9751035.npz',
 'at_DTU/npz_files_image_based/spalling/synth_dtu_spall_10/synth_dtu_spall_10_12909267.npz',
 'at_DTU/npz_files_image_based/spalling/synth_dtu_spall_10/synth_dtu_spall_10_14721877.npz',
 'at_DTU/npz_files_image_based/spalling/synth_dtu_spall_10/synth_dtu_spall_10_16710333.npz',
 'at_DTU/npz_files_image_based/spalling/synth_dtu_spall_12/synth_dtu_spall_12_9341931.npz',
 'at_DTU/npz_files_image_based/spalling/synth_dtu_spall_12/synth_dtu_spall_12_10330089.npz',
 'at_DTU/npz_files_image_based/spalling/synth_dtu_spall_12/synth_dtu_spall_12

In [14]:
with open(text_file,"w") as f:
    for file in with_anns_list:
        f.writelines(file + "\n")

In [4]:
without_lab_list = []
count = 0
with open(text_file,"r") as f:
    files = f.readlines()
    for file in files:
        #print(file)
        count += 1
        if file.startswith("at_"):
            continue
        without_lab_list.append(file)
print("number of anns ",count)

number of anns  4700


In [5]:
without_lab_list

['dset_1/npz_files_event_based/crack/crack_11/crack_11_1216658.npz\n',
 'dset_1/npz_files_event_based/crack/crack_11/crack_11_1285581.npz\n',
 'dset_1/npz_files_event_based/crack/crack_11/crack_11_5830960.npz\n',
 'dset_1/npz_files_event_based/crack/crack_11/crack_11_5145123.npz\n',
 'dset_1/npz_files_event_based/crack/crack_11/crack_11_4935904.npz\n',
 'dset_1/npz_files_event_based/crack/crack_11/crack_11_1456485.npz\n',
 'dset_1/npz_files_event_based/crack/crack_18/crack_18_117607.npz\n',
 'dset_1/npz_files_event_based/crack/crack_18/crack_18_10163380.npz\n',
 'dset_1/npz_files_event_based/crack/crack_18/crack_18_10349578.npz\n',
 'dset_1/npz_files_event_based/crack/crack_18/crack_18_10702304.npz\n',
 'dset_1/npz_files_event_based/crack/crack_18/crack_18_10231420.npz\n',
 'dset_1/npz_files_event_based/crack/crack_18/crack_18_9772429.npz\n',
 'dset_1/npz_files_event_based/crack/crack_18/crack_18_8810006.npz\n',
 'dset_1/npz_files_event_based/crack/crack_18/crack_18_8448646.npz\n',
 'd

In [6]:
text_file = "/media/udayanga/data_2/latest_dataset_2/latest_dataset/night_outdoor_and_daytime_train_files_event_based_nolab.txt"

In [7]:
with open(text_file,"w") as f:
    for file in without_lab_list:
        f.writelines(file)