In [3]:
import os
import glob
src_folder = "/media/udayanga/data_2/shon_data/DATA/Laboratory_data/At_DTU_part_2/spalling/json_labels"

for sub_folder in os.listdir(src_folder):
    json_files = glob.glob(os.path.join(src_folder,sub_folder) + "/*_evframe.json")
    png_files = glob.glob(os.path.join(src_folder,sub_folder) + "/*_evframe.png")
    if len(json_files) != len(png_files):
        print(sub_folder)

In [34]:
from pathlib import Path
import os

In [53]:
def traverse_pathlib(path):
    count_desired = 0
    count_event_npy = 0
    path_obj = Path(path)
    for item in path_obj.rglob('*'):
        if item.is_dir():
            #if "json_labels" in item.read_text():
            #if item.name == "json_labels":
            #    print(f"Directory: {item}")
                #count_desired += 1
            s = [element for element in os.listdir(str(item.parent) + "/" + str(item.name))if os.path.isdir(os.path.join(str(item.parent),str(item.name),element))]
            if len(s) == 0:
                mm = [element for element in os.listdir(str(item.parent) + "/" + str(item.name)) if ".npy" in element]
                if len(mm) == 0:
                    print(item)
                count_desired += 1

        else:
            """if item.suffix == ".npy":
                    if "frame_label" in str(item.name):
                        count_desired += 1
                    else:
                         count_event_npy += 1"""


    print(count_desired)
    #print(count_event_npy)

In [54]:
path = "/media/udayanga/data_2/shon_data/DATA_TO_HOST/ev-CIVIL_dataset/Field_dataset/"
traverse_pathlib(path)

/media/udayanga/data_2/shon_data/DATA_TO_HOST/ev-CIVIL_dataset/Field_dataset/field_data_day/dset_6/crack/h5_files
319


In [1]:
import numpy as np
src = "/media/udayanga/data_2/shon_data/DATA_TO_HOST/ev-CIVIL_dataset/Field_dataset/field_data_day/dset_2/spalling_36/spalling_36_label.npy"

qq = np.load(src)


In [69]:
def traverse_pathlib(path):
    count_desired = 0
    count_event_npy = 0
    path_obj = Path(path)
    for item in path_obj.rglob('*'):
        if item.is_dir():
             continue
        else:
            if item.suffix == ".npy":
                full_path = os.path.join(str(item.parent),str(item.name))
                unsorted_arr = np.load(full_path)
                sorted_array = unsorted_arr[unsorted_arr[:,0].argsort()]
                
                print(item.name," ",np.argmin(sorted_array[:,0]))
                np.save(full_path,sorted_array)
                if "frame_label" in str(item.name):
                    count_desired += 1
                else:
                    count_event_npy += 1
    
    print(count_desired)
    print(count_event_npy)  

In [70]:
path = "/media/udayanga/data_2/shon_data/DATA_TO_HOST/ev-CIVIL_dataset/Laboratory_dataset/"
traverse_pathlib(path)

1_march_crack_3_label.npy   0
1_march_crack_12_label.npy   0
1_march_crack_11_label.npy   0
1_march_crack_20_label.npy   0
1_march_crack_6_label.npy   0
1_march_crack_19_label.npy   0
1_march_crack_9_label.npy   0
1_march_crack_2_label.npy   0
1_march_crack_4_label.npy   0
1_march_crack_14_label.npy   0
1_march_crack_8_label.npy   0
1_march_crack_7_label.npy   0
1_march_crack_16_label.npy   0
1_march_crack_17_label.npy   0
1_march_crack_5_label.npy   0
1_march_crack_18_label.npy   0
1_march_crack_13_label.npy   0
1_march_crack_10_label.npy   0
night_crack_6_label.npy   0
night_crack_1_label.npy   0
night_crack_3_label.npy   0
night_crack_11_label.npy   0
night_crack_13_label.npy   0
night_crack_10_2_label.npy   0
night_crack_5_label.npy   0
night_crack_12_label.npy   0
night_crack_7_label.npy   0
8_march_normal_87_label.npy   0
8_march_normal_81_label.npy   0
8_march_normal_80_label.npy   0
8_march_normal_82_label.npy   0
25_Feb_8_label.npy   0
25_Feb_16_label.npy   0
25_Feb_14_label.n

In [6]:
ss = qq[qq[:,0].argsort()]

In [9]:
np.save(src,ss)

In [10]:
dest = "/media/udayanga/data_2/shon_data/DATA_TO_HOST/ev-CIVIL_dataset/Field_dataset/field_data_day/dset_2/spalling_36/spalling_36_label.npy"

In [12]:
np.argmin(np.load(dest)[:,0])

0

In [8]:
np.argmin(ss[:,0])

0

In [35]:
src = "/media/udayanga/data_2/shon_data/DATA_TO_HOST/DATA"

In [38]:
traverse_pathlib(src)

0


In [68]:
import numpy as np
sss = np.load("/media/udayanga/data_2/Final_Data_set/To_Labelled/tunnel_selected/h5_files/crack/crack_with_filt_1/crack_with_filt_1_new_label.npy")

In [42]:
sss[:,0]

array([21011132., 10811886., 11404782.,  6657749.,  7250266.])

In [69]:
import h5py
src_h5 = "/media/udayanga/data_2/Final_Data_set/To_Labelled/tunnel_selected/h5_files/crack/crack_with_filt_1/crack_with_filt_1_events.h5"
file = h5py.File(src_h5,"r")

In [65]:
for key in file.keys():
    
    
    print(key)

event_timestamp
polarity
x
y


In [66]:
sss_int = sss[:,0].astype(np.int64)

In [71]:
count = 0
for element in sss_int:
    print("index ",element)
    tstamp = file["event_timestamp"][element]
    print("tstamp ",tstamp)
    sss[count,0] = tstamp
    count += 1

index  21011132
tstamp  553434509
index  10811886
tstamp  551799927
index  11404782
tstamp  551896057
index  6657749
tstamp  551126831
index  7250266
tstamp  551223022


In [57]:
sss

array([[5.53434509e+08, 5.53434509e+08, 5.53434509e+08, 5.53434509e+08,
        5.53434509e+08, 5.53434509e+08],
       [5.51799927e+08, 5.51799927e+08, 5.51799927e+08, 5.51799927e+08,
        5.51799927e+08, 5.51799927e+08],
       [5.51896057e+08, 5.51896057e+08, 5.51896057e+08, 5.51896057e+08,
        5.51896057e+08, 5.51896057e+08],
       [5.51126831e+08, 5.51126831e+08, 5.51126831e+08, 5.51126831e+08,
        5.51126831e+08, 5.51126831e+08],
       [5.51223022e+08, 5.51223022e+08, 5.51223022e+08, 5.51223022e+08,
        5.51223022e+08, 5.51223022e+08]])

In [72]:
np.save("/media/udayanga/data_2/Final_Data_set/To_Labelled/tunnel_selected/h5_files/crack/crack_with_filt_1/crack_with_filt_1_label.npy",sss)

In [56]:
sss[:,0]

array([5.53434509e+08, 5.51799927e+08, 5.51896057e+08, 5.51126831e+08,
       5.51223022e+08])

In [50]:
file["event_timestamp"][sss[:,0].astype(np.int64)]

TypeError: Indexing elements must be in increasing order

In [1]:
import os

In [26]:
full_new_path_list = []
src_file = "/home/udayanga/Desktop/temp_files/night_outdoor_and_daytime_train_files_event_based_nolab.txt"
with open(src_file) as f:
    npz_files = f.readlines()
    for file in npz_files:
        sub_folder = file.rsplit("/",2)[1]
        base_folder = file.split("/",1)[0]
        #print("base folder and sub folder ",base_folder," ",sub_folder)
        full_new_path = base_folder + "/" + sub_folder
        full_new_path_list.append(full_new_path)

In [27]:
len(full_new_path_list)

1711

In [28]:
desired_set = set(full_new_path_list)

In [29]:
len(desired_set)

133

In [30]:
from pathlib import Path

def traverse_directory(path):
    count = 0
    new_set = []
    for item in path.rglob('*'):
        if item.is_dir():
            #print(item.parent)
            desired_name = str(item.parent).rsplit("/",1)[1] + "/" + item.name
            print(desired_name)
            if  desired_name in desired_set:
                print(desired_name)
                count += 1
                new_set.append(desired_name)

        elif item.is_file():
            continue
    print(count)
    return new_set

In [31]:
path = Path("/media/udayanga/data_2/shon_data/DATA_TO_HOST/ev-CIVIL_dataset/Field_dataset")
new_set = traverse_directory(path)

Field_dataset/day_time_challenge
Field_dataset/field_data_day
Field_dataset/Night_outdoor
Field_dataset/tunnel_selected
Field_dataset/other_data
day_time_challenge/crack_133
day_time_challenge/crack_89
day_time_challenge/spalling_57
day_time_challenge/crack_88
day_time_challenge/spalling_31
day_time_challenge/crack_115
field_data_day/at_eth
field_data_day/dset_2
field_data_day/dset_1
field_data_day/dset_3
field_data_day/dset_5
field_data_day/dset_4
field_data_day/dset_6
at_eth/synth_spalling_121
at_eth/synth_spalling_57
at_eth/synth_spalling_19
at_eth/synth_spalling_85
dset_2/crack_72
dset_2/spalling_45
dset_2/crack_102
dset_2/crack_102
dset_2/crack_109
dset_2/crack_109
dset_2/crack_82
dset_2/crack_82
dset_2/crack_93
dset_2/crack_93
dset_2/crack_100
dset_2/spalling_42
dset_2/spalling_27
dset_2/spalling_27
dset_2/spalling_28
dset_2/crack_70
dset_2/crack_70
dset_2/spalling_51
dset_2/spalling_51
dset_2/crack_79
dset_2/crack_79
dset_2/crack_60
dset_2/spalling_33
dset_2/spalling_41
dset_2/c

In [32]:
for file in desired_set:
    if file not in new_set:
        print(file)

In [33]:
len(new_set)

133

In [34]:
to_write_list = []
prefix = "Field_dataset"
for file in new_set:
    to_write_list.append(prefix + "/" + file)



In [35]:
len(to_write_list)

133

In [36]:
to_write_file = "/media/udayanga/data_2/shon_data/DATA/train_samples_from_field"
with open(to_write_file,"w") as f:
    for element in to_write_list:
        f.writelines(element + "\n")

In [23]:
tunnel_files = os.listdir("/media/udayanga/data_2/shon_data/DATA_TO_HOST/ev-CIVIL_dataset/Field_dataset/tunnel_selected")

In [24]:
print(tunnel_files)

['crack_with_filt_1', 't_spall_10', 't_spall_13', 't_spall_9', 't_spall_7', 't_crack_3', 't_spall_1', 't_spall_5']


In [25]:
with open(to_write_file,"a") as f:
    for file in tunnel_files:
        f.writelines("tunnel_selected/" + file + "\n")

In [3]:
import numpy as np
kk = np.load("/media/udayanga/data_2/shon_data/DATA_TO_HOST/ev-CIVIL_dataset/Field_dataset/field_data_day/dset_2/spalling_36/spalling_36_label.npy")

In [6]:
base_path = "/media/udayanga/data_2/shon_data/DATA_TO_HOST/ev-CIVIL_dataset/Field_dataset/field_data_day"

In [7]:
ee = np.load(base_path + "/dset_2/crack_76/crack_76_label.npy")

In [8]:
ee

array([[ 7.79291600e+06,  0.00000000e+00,  9.66462094e+01,
         5.32907052e-15,  6.28158845e+01,  1.99223827e+02],
       [ 6.36615700e+06,  0.00000000e+00,  1.02241877e+02,
         5.32907052e-15,  9.33212996e+01,  2.58249097e+02],
       [ 7.81793400e+06,  0.00000000e+00,  9.08700361e+01,
         1.80505415e-01,  6.28158845e+01,  1.99223827e+02],
       [ 7.91806400e+06,  0.00000000e+00,  7.64296029e+01,
         5.32907052e-15,  6.28158845e+01,  1.99223827e+02],
       [ 7.89302800e+06,  0.00000000e+00,  8.22057762e+01,
         1.80505415e-01,  6.28158845e+01,  1.99223827e+02],
       [ 8.14333600e+06,  0.00000000e+00,  4.22743682e+00,
        -8.88178420e-15,  9.63898917e+01,  2.28646209e+02],
       [ 5.74039200e+06,  0.00000000e+00,  1.95382671e+02,
         5.32907052e-15,  6.96750903e+01,  2.58967615e+02],
       [ 5.79045800e+06,  0.00000000e+00,  2.05129964e+02,
         5.32907052e-15,  6.96750903e+01,  2.58967615e+02],
       [ 6.94186100e+06,  0.00000000e+00,  1.632

In [22]:
np.argmin(kk[:,0])

61

In [15]:
tt = kk[kk[:, 0].argsort()]

In [16]:
np.min(tt[:,0])

10490312.0

In [17]:
kk

array([[1.33402930e+07, 1.00000000e+00, 0.00000000e+00, 9.63942040e+01,
        1.96449319e+02, 9.31368096e+01],
       [1.49652880e+07, 1.00000000e+00, 2.85930408e+01, 1.02294355e+02,
        2.29883510e+02, 9.31368096e+01],
       [1.39902940e+07, 1.00000000e+00, 4.38729198e+00, 1.48890422e+02,
        2.32455371e+02, 9.26829518e+01],
       ...,
       [1.40152880e+07, 1.00000000e+00, 9.83358548e+00, 1.45713417e+02,
        2.32455371e+02, 9.26829518e+01],
       [1.33902870e+07, 1.00000000e+00, 0.00000000e+00, 1.01840498e+02,
        1.89036309e+02, 8.73879443e+01],
       [1.53903050e+07, 1.00000000e+00, 7.06505295e+01, 1.10161224e+02,
        2.29883510e+02, 9.31368096e+01]])

In [20]:
np.argmin(tt[:,0])

0

In [24]:
tt[:,1]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
a = np.array([1,2,4,4,4,5,6])

In [35]:
match_frame_tstamp = np.min(a[(a >= 3)])

In [36]:
match_boxes = a[a == match_frame_tstamp]

In [37]:
match_boxes

array([4, 4, 4])

In [2]:
import cv2

def convert_avi_to_mp4(input_file, output_file, fps=30):
    # Open the input AVI file
    cap = cv2.VideoCapture(input_file)
    
    # Get the codec and frame size of the input video
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')  # Choose the codec for MP4 (H264 is the default)
    frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    
    # Create a VideoWriter object to write the MP4 file
    out = cv2.VideoWriter(output_file, fourcc, fps, (frame_width, frame_height))
    
    # Read and write each frame until the end of the video
    while cap.isOpened():
        ret, frame = cap.read()
        if ret:
            out.write(frame)
        else:
            break
    
    # Release resources
    cap.release()
    out.release()
    cv2.destroyAllWindows()


In [4]:
import os
os.getcwd()

'/media/udayanga/data_2/shon_data/CODE'

In [6]:
os.chdir("/media/udayanga/data_2/shon_data/visualization_videos")
os.getcwd()

'/media/udayanga/data_2/shon_data/visualization_videos'

In [18]:
input_file = 'street_lighting.avi'
output_file = 'street_lighting.mp4'
convert_avi_to_mp4(input_file, output_file)